### ISSUE TITLE
What types are available for input/output?

### ISSUE THREAD

**Issue by BSouzaDock** [slack-samples/bolt-python-custom-step-template#13]
I'm having trouble filling out the app manifest with the correct input/output types.

I found this documentation: https://api.slack.com/automation/types

In the project example, `slack#/types/user_id` is used.

I don't know if I'm doing something wrong, but I tried `slack#/types/string`, `types/string`, `types#/string` and I always get the following error: `Unknown type found - types/string (validate_parameter_types)`

I believe there is a lack of explanation on how to fill in the inputs correctly.

**Comment by WilliamBergamin** [comment]
@BSouzaDock You should now be able to edit the `function` definitions through the [app settings](https://api.slack.com/apps) page

Let me know if this helps 🙏

**Comment by zimeg** [comment]
📝 Going to close this as **complete** with the above notes and [this API documentation that lists all of the types](https://api.slack.com/automation/types#all), but please feel free add to this thread with other questions!
