### ISSUE TITLE
Socket Mode and Request URLs are overridden in the manifest when installing with the CLI

### ISSUE THREAD

**Issue by Steven-Diaz-de-Leon** [slack-samples/bolt-python-custom-step-template#9]
I'm not sure if this is the right place to report this issue but if its not I would appreciate if you could point me to the right place to do so.

The issue I am seeing is when I try to update certain parts of the manifest, it seems the changes dont take affect when I view the manifest in the app page. For example I have set `socket_mode_enabled` to false but it is always set to true upon running `slack run`. Another thing that is not updating is the event_subscriptions section.

However adding a new function does update the manifest correctly as expected with the new functions although the other settings are still not updated (like socket mode enabled).

Below is my manifest

```
{
  "display_information": {
    "name": "observability-bot"
  },
  
  "outgoing_domains": [],
  "settings": {
    "interactivity": {
      "is_enabled": true,
      "request_url": "https://<My-Server>ngrok-free.app/slack/events"
    },
    "event_subscriptions": {
      "request_url": "https://<My-Server>.ngrok-free.app/slack/events"
    },
    "org_deploy_enabled": true,
    "socket_mode_enabled": false
  },
    "features": {
    "bot_user": {
      "display_name": "observability-bot"
    },
    "app_home": {
      "messages_tab_enabled": true
    }
  },
  "oauth_config": {
    "scopes": {
      "bot": ["chat:write", "channels:history", "channels:read", "commands", "files:write", "im:history", "im:read", "im:write"]
    }
  },
  "functions": {
    #<my function definitions>
  }
}
```

**Comment by zimeg** [comment]
Hey @Steven-Diaz-de-Leon 👋  This is a great place for the report, thanks for sending it in!

At this moment the CLI is a bit opinionated about the manifest values set during installation and will override values to ensure the local `run` command works as expected. At least in the context of developing with only the CLI since this isn't working as you'd expect...

We're planning to improve this so that these manifest settings are used in an app installation, so I'll mark this as a "bug" for now, but as a workaround you'll have to upload the `manifest.json` to [App Config](https://api.slack.com/apps) (via the "App Manifest" tab) and run your app directly with `python3 app.py` (or similar).

**Comment by zimeg** [comment]
For a bit more context, the CLI is overriding values to make the app compatible with Socket Mode for the local `run`. Right now these values include:

```json
{
  "settings":
    "socket_mode_enabled": true,
    "interactivity": {
      "is_enabled": true,
      "request_url": "",
      "message_menu_options_url": ""
    },
    "event_subscriptions": {
      "request_url": ""
    }
}
```

**Comment by Steven-Diaz-de-Leon** [comment]
I see, thanks for the clarification, I will use the workaround.

**Comment by zimeg** [comment]
@Steven-Diaz-de-Leon meant to follow up sooner about this, but Slack CLI `v2.29.1` will avoid overwriting these manifest values when using the either the `install` or `deploy` command! At least when the function runtime of the app is "remote", which is the most common for Bolt apps.

For a bit more detail: Local apps used with `run` will still continue to append a `(local)` tag, but all of the other manifest values should be unchanged, similar to an `install`.

With that fix landing and app manifests for Bolt apps now being installed as-is, I think we can close this issue! Thanks again for raising this 🙏
